name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup SSH and deploy
        env:
          DEPLOY_REPO: foufan/foufan.github.io
          SSH_PRIVATE_TOKEN: ${{ secrets.SSH_PRIVATE_TOKEN }}
        run: |
          # 设置 SSH 配置
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_TOKEN}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 添加 GitHub 的 SSH key 到 known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 克隆目标仓库
          git clone git@github.com:foufan/foufan.gihub.io.git deploy_repo
          cd deploy_repo

          # 清空目标仓库并复制新的构建产物
          rm -rf *
          cp -r ../dist/* .

          # 提交并推送更改
          git add .
          git commit -m "Deploy from foufan/foufan"
          git push origin main
