name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Print pnpm store path and save as environment variable
        run: |
          echo "store-path=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.store-path }}
            node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Build the project
        run: pnpm run build

      - name: Create or update _config.yml file
        run: |
          echo "include:" > dist/_config.yml
          echo "  - _astro" >> dist/_config.yml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages git@github.com:foufan/foufan.github.io.git deploy

      - name: Backup and restore CNAME file
        run: |
          if [ -f deploy/CNAME ]; then
            mv deploy/CNAME CNAME
          fi
          rsync -av --delete --exclude '.git' --exclude 'CNAME' dist/ deploy/
          if [ -f CNAME ]; then
            mv CNAME deploy/CNAME
          fi

      - name: Commit and push to gh-pages branch
        run: |
          cd deploy
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Deploy to GitHub Pages"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
